### ISSUE TITLE
Support Protobuf.jl versions 1.0 and up

### ISSUE THREAD

**Issue by lambe** [DrChainsaw/ONNXNaiveNASflux.jl#84]
I'm using this package to save ONNX-format models alongside some work that uses PProf for profiling my code. PProf currently uses a recent version of Protobuf.jl so I can't have both packages installed at the same time because of the dependency conflict. I'm currently working around that issue by only installing this package when I want to save an ML model in ONNX format and then uninstalling when I'm done, but that could be improved.

Are there any plans to upgrade to version 1 of Protobuf.jl and up?

I've played around with a solution and I'm happy to share my own work-in-progress if you're interested - it looks like some restructuring of the serialize and deserialize code is in order.

**Comment by DrChainsaw** [comment]
We should definitely update Protobuf.jl. I just kinda forgot about it.

If you have a work in progress then feel free to submit a PR. Does the restructuring of the serialize/deserialize code follow from Protobuf 1.0 or is it separate?

**Comment by lambe** [comment]
See #85 

So far, I generated new Julia code from the ONNX protobufs and updated some of the other files so that precompilation works. Unit tests are still broken and I'm not quite sure how to fix them - an extra set of eyes would be helpful.

**Comment by DrChainsaw** [comment]
Closed by #85
