### ISSUE TITLE
How can I rename the input and output layers?

### ISSUE THREAD

**Issue by alicewith** [DrChainsaw/ONNXNaiveNASflux.jl#94]
Hi, all. I want to export my model with specifying each name of the input and output layers, but I have no idea how I can do it.

![image](https://github.com/user-attachments/assets/550eb928-990c-4f62-a7a4-e4575f547ded)

The above is my simple model. How can I rename from `data_0` and `softmax_0` to something I want, say `input` and `output`?
Thanks!

**Comment by DrChainsaw** [comment]
Hi,

The input can easily be named by providing it when saving, like this:

```julia
model = Chain(
       Dense(784, 32, sigmoid),
       Dense(32, 10),
       softmax)

save("model_inputname.onnx", model, "input" => (784,:Batch)
```

The outputs don't have a convenient API for naming, so you have to resort to the not as easy to use `namestrat` argument which takes a function which returns the name for each layer. Beware that you have to make sure each name is unique or else the ONNX file is invalid. Also note that it is not fully consistent what you get as input to it so you might want to print out the input argument just to see what it is.

Here are two examples
```julia
namestrat1 = function(layer)
           layer == "softmax" && return "output"
           i = findfirst(==(layer), model.layers)
           return "Layer_$i"
        end

save("model_namestrat1.onnx", model, "input" => (784,:Batch); namestrat=namestrat1)

# This lets ONNXNaiveNASflux ensure names are unique, but you'll always get a running number appended to the name
namestrat2 = ONNXNaiveNASflux.name_runningnr() do layer
           layer == "softmax" && return "output"
           ONNXNaiveNASflux.genname(layer)
     end

save("model_namestrat2.onnx", model, "input" => (784,:Batch); namestrat=namestrat2)
```

If you make use of the CompGraph format from NaiveNASflux it will use the names used for the layers
```julia
modelgraph = let
           input = denseinputvertex("input", 748)
           layer1 = fluxvertex("layer_1", Dense(nout(input) => 32, sigmoid), input)
           layer2 = fluxvertex("layer_2", Dense(nout(layer1) => 10), layer1)
           output = invariantvertex("output", sigmoid, layer2)
           CompGraph(input, output)
     end

save("model_graph.onnx", modelgraph)
```

**Comment by DrChainsaw** [comment]
Great, let's keep this open for now as it at least serves as extra documentation.

Do you have any suggestions for the naming API? 

One must be a little bit careful since the names are used for defining the model and therefore must be unique, so there is so users can't use any names they want. Afaik onnx does not have any special treatment of output nodes, they are just like any other node.

I suppose one could do something similar to e.g. DataFrames and have some `makeunique` flag combined with some more relaxed naming API.

**Comment by alicewith** [comment]
I think that since specifying the name of layers is available upon Flux.Chain, keeping its name into the ONNX model is reasonable.
You can refer the code snippet to implement such feature:

```julia
julia> model = Chain(input = Dense(784 => 32), layer1 = Dense(32 => 32), layer2 = Dense(32 => 32), output = Dense(32 => 10))
julia> fieldnames(typeof(model.layers))
(:input, :layer1, :layer2, :output)
```

Note that although omitting the layer name partially in Flux.Chain should occur some errors, omitting all names works well as specifying all names works too, so the API might not be broken.

If someone is hesitating to specify all layer names, sub-chain the internal layers is possible:

```julia
julia> model = Chain(input = Chain(Dense(784 => 32), Dense(32 => 32), Dense(32 => 32)), output = Dense(32 => 10))
julia> fieldnames(typeof(model.layers))
(:input, :output)
```

**Comment by DrChainsaw** [comment]
Ah, the naming capability of Flux is newer than this package and I had completely forgot about it.

It makes sense to use those names when creating the onnx model. I will look into it when time permits.
